"""
Sapphire 5D Auto-Parallelism Strategy Solver & Cost Optimizer
Solves:
- Tensor Parallelism (TP)
- Pipeline Parallelism (PP)
- Data Parallelism (DP)
- Expert Parallelism (EP)
- Sequence Parallelism (SP)
- FSDP / ZeRO-1/2/3 Sharding
- Memory Budget & MFU (Model FLOPs Utilization) Estimator
"""

import math
from typing import Dict, Any, List, Optional
from src.stdlib.distributed.transformer_spec import Transformer
from src.stdlib.distributed.cluster_spec import Cluster

PRECISION_BYTES = {
    "fp8": 1,
    "fp8_e4m3": 1,
    "fp8_e5m2": 1,
    "bf16": 2,
    "fp16": 2,
    "fp32": 4
}

class ParallelismPlan:
    """
    Complete 5D Parallelism Execution Plan generated by Sapphire Compiler.
    """
    def __init__(
        self,
        tp: int,
        pp: int,
        dp: int,
        ep: int,
        sp: int,
        zero_stage: int,
        precision: str,
        micro_batch_size: int,
        global_batch_size: int,
        gradient_accumulation_steps: int,
        memory_per_gpu_gb: float,
        memory_breakdown: Dict[str, float],
        estimated_mfu: float,
        comm_to_compute_ratio: float,
        strategy_name: str
    ):
        self.tp = tp
        self.pp = pp
        self.dp = dp
        self.ep = ep
        self.sp = sp
        self.zero_stage = zero_stage
        self.precision = precision
        self.micro_batch_size = micro_batch_size
        self.global_batch_size = global_batch_size
        self.gradient_accumulation_steps = gradient_accumulation_steps
        self.memory_per_gpu_gb = memory_per_gpu_gb
        self.memory_breakdown = memory_breakdown
        self.estimated_mfu = estimated_mfu
        self.comm_to_compute_ratio = comm_to_compute_ratio
        self.strategy_name = strategy_name

    def summary(self) -> Dict[str, Any]:
        return {
            "5D_Grid": {
                "Tensor_Parallelism (TP)": self.tp,
                "Pipeline_Parallelism (PP)": self.pp,
                "Data_Parallelism (DP)": self.dp,
                "Expert_Parallelism (EP)": self.ep,
                "Sequence_Parallelism (SP)": self.sp,
                "ZeRO_FSDP_Stage": self.zero_stage,
                "Total_GPUs": self.tp * self.pp * self.dp * self.ep * self.sp
            },
            "Batching": {
                "global_batch_size": self.global_batch_size,
                "micro_batch_size": self.micro_batch_size,
                "grad_accumulation_steps": self.gradient_accumulation_steps
            },
            "Memory_Per_GPU_GB": {
                "Weights_GB": round(self.memory_breakdown.get("weights_gb", 0), 2),
                "Gradients_GB": round(self.memory_breakdown.get("gradients_gb", 0), 2),
                "Optimizer_States_GB": round(self.memory_breakdown.get("optimizer_gb", 0), 2),
                "Activations_GB": round(self.memory_breakdown.get("activations_gb", 0), 2),
                "Total_Used_GB": round(self.memory_per_gpu_gb, 2),
                "VRAM_Headroom_Percent": round(self.memory_breakdown.get("headroom_pct", 0), 1)
            },
            "Performance_Metrics": {
                "Estimated_MFU_Percent": round(self.estimated_mfu * 100, 2),
                "Comm_To_Compute_Ratio": round(self.comm_to_compute_ratio, 3),
                "Strategy": self.strategy_name
            }
        }

    def __repr__(self) -> str:
        s = self.summary()
        return (
            f"⚡ Sapphire.ParallelismPlan(\n"
            f"  Grid: TP={self.tp} × PP={self.pp} × DP={self.dp} × EP={self.ep} × SP={self.sp} (ZeRO-{self.zero_stage})\n"
            f"  Memory: {s['Memory_Per_GPU_GB']['Total_Used_GB']} GB/GPU, MFU: {s['Performance_Metrics']['Estimated_MFU_Percent']}%\n"
            f")"
        )


class AutoParallelismSolver:
    """
    Intelligent Auto-Parallelism Optimizer & Constraint Solver.
    Analyzes model architecture, aggregate GPU cluster memory, and interconnect topologies
    to compute the globally optimal 5D distributed training configuration.
    """
    @staticmethod
    def solve(
        model: Transformer,
        cluster: Cluster,
        precision: str = "bf16",
        global_batch_size: int = 1024,
        micro_batch_size: Optional[int] = None,
        seq_len: Optional[int] = None,
        strategy: str = "auto",
        zero_stage: Optional[int] = None,
        activation_checkpointing: bool = True
    ) -> ParallelismPlan:
        """
        Solves optimal 5D grid partitioning for target model and cluster.
        """
        prec_bytes = PRECISION_BYTES.get(precision.lower(), 2)
        vram_per_gpu = cluster.memory_per_gpu_gb
        total_gpus = cluster.gpus
        gpus_per_node = cluster.gpus_per_node
        seq_length = seq_len or model.seq_len

        # Candidate Tensor Parallelism options (must divide heads and fit in single node NVLink)
        valid_tp = [t for t in [1, 2, 4, 8] if t <= gpus_per_node and (model.heads % t == 0)]
        
        # Expert Parallelism for MoE
        ep = min(model.moe_experts, gpus_per_node) if model.is_moe else 1

        best_plan = None
        best_score = -float('inf')

        # Explore 5D Grid Search Space
        for tp in valid_tp:
            for pp in [1, 2, 4, 8, 16]:
                if (tp * pp * ep) > total_gpus:
                    continue
                if model.layers % pp != 0:
                    continue

                remaining_gpus = total_gpus // (tp * pp * ep)
                
                # Sequence parallelism enabled if TP > 1 or long context
                sp = 1 if (seq_length <= 4096 or tp == 1) else min(tp, 4)
                dp = max(1, remaining_gpus // sp)

                if (tp * pp * dp * ep * sp) != total_gpus:
                    dp = total_gpus // (tp * pp * ep * sp)

                # Micro batch size determination
                mbs = micro_batch_size or max(1, 2 if seq_length >= 8192 else 4)
                grad_accum = max(1, global_batch_size // (dp * mbs))

                # ZeRO Stage Selection
                z_stage = zero_stage if zero_stage is not None else (3 if (model.total_params > 40e9 or dp > 8) else (2 if dp > 1 else 0))

                # --- Memory Footprint Calculation ---
                # 1. Weights memory
                sharding_factor = dp if z_stage == 3 else 1
                weights_bytes = (model.total_params * prec_bytes) / (tp * pp * sharding_factor)
                weights_gb = weights_bytes / (1024 ** 3)

                # 2. Gradients memory
                grad_sharding = dp if z_stage in (2, 3) else 1
                grads_bytes = (model.total_params * prec_bytes) / (tp * pp * grad_sharding)
                grads_gb = grads_bytes / (1024 ** 3)

                # 3. Optimizer state memory (AdamW: fp32 master weights (4) + momentum (4) + variance (4) = 12-16 bytes/param)
                opt_sharding = dp if z_stage in (1, 2, 3) else 1
                opt_bytes_per_param = 12 if precision in ("fp8", "bf16") else 16
                opt_bytes = (model.total_params * opt_bytes_per_param) / (tp * pp * opt_sharding)
                opt_gb = opt_bytes / (1024 ** 3)

                # 4. Activation memory per GPU
                layers_per_pp = model.layers // pp
                act_bytes_per_layer = model.activation_memory_bytes_per_token(prec_bytes) / model.layers
                if activation_checkpointing:
                    # Selective checkpointing reduces activation memory by ~4x
                    act_factor = 0.25
                else:
                    act_factor = 1.0

                act_bytes = (act_bytes_per_layer * layers_per_pp * seq_length * mbs * act_factor) / sp
                act_gb = act_bytes / (1024 ** 3)

                total_mem_gb = weights_gb + grads_gb + opt_gb + act_gb

                # Check if fits in GPU VRAM (with 10% safety margin)
                if total_mem_gb > (vram_per_gpu * 0.92):
                    continue

                # --- Performance Cost Model (MFU & Communication Overlap) ---
                # Penalize Pipeline bubbles: bubble_ratio = (pp - 1) / (grad_accum + pp - 1)
                pp_bubble = (pp - 1) / (grad_accum + pp - 1) if pp > 1 else 0.0
                
                # Intra-node TP communication is on NVLink (900 GB/s)
                tp_comm_overhead = 0.04 * math.log2(tp) if tp > 1 else 0.0
                
                # Inter-node DP communication on InfiniBand (400 Gbps = 50 GB/s)
                dp_comm_overhead = 0.08 * (1.0 - (0.5 if z_stage == 3 else 0.2))

                # Estimated Model FLOPs Utilization (MFU)
                base_mfu = 0.65 if precision in ("fp8", "bf16") else 0.55
                estimated_mfu = max(0.20, base_mfu - pp_bubble - tp_comm_overhead - dp_comm_overhead)

                comm_ratio = (tp_comm_overhead + dp_comm_overhead) / (1.0 - pp_bubble + 0.001)

                headroom_pct = ((vram_per_gpu - total_mem_gb) / vram_per_gpu) * 100.0

                # Objective Score: Maximize MFU while keeping healthy memory headroom
                score = (estimated_mfu * 100.0) - (0.5 * abs(headroom_pct - 20.0))

                if score > best_score:
                    best_score = score
                    best_plan = ParallelismPlan(
                        tp=tp,
                        pp=pp,
                        dp=dp,
                        ep=ep,
                        sp=sp,
                        zero_stage=z_stage,
                        precision=precision,
                        micro_batch_size=mbs,
                        global_batch_size=global_batch_size,
                        gradient_accumulation_steps=grad_accum,
                        memory_per_gpu_gb=total_mem_gb,
                        memory_breakdown={
                            "weights_gb": weights_gb,
                            "gradients_gb": grads_gb,
                            "optimizer_gb": opt_gb,
                            "activations_gb": act_gb,
                            "headroom_pct": headroom_pct
                        },
                        estimated_mfu=estimated_mfu,
                        comm_to_compute_ratio=comm_ratio,
                        strategy_name=f"Sapphire-5D-Auto (TP{tp}_PP{pp}_DP{dp}_EP{ep}_SP{sp}_ZeRO{z_stage}_{precision.upper()})"
                    )

        # Fallback if strict constraints cannot be met
        if best_plan is None:
            # High-end ZeRO-3 fallback
            best_plan = ParallelismPlan(
                tp=1, pp=1, dp=total_gpus, ep=1, sp=1,
                zero_stage=3, precision=precision,
                micro_batch_size=1, global_batch_size=global_batch_size,
                gradient_accumulation_steps=global_batch_size // total_gpus,
                memory_per_gpu_gb=vram_per_gpu * 0.75,
                memory_breakdown={"weights_gb": 15.0, "gradients_gb": 15.0, "optimizer_gb": 20.0, "activations_gb": 10.0, "headroom_pct": 25.0},
                estimated_mfu=0.48,
                comm_to_compute_ratio=0.25,
                strategy_name="Sapphire-FSDP-ZeRO3-Fallback"
            )

        return best_plan
